theme: jekyll-theme-time-machine
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "strikethrough", "superscript", "table","disable_indented_code_blocks","space_after_headers"]
